### ISSUE TITLE
Chemistry Resolution Fails when building against libpbconsensus

### ISSUE THREAD

**Issue by bnbowman** [PacificBiosciences/ConsensusCore2#1]
pblaa works fine with ConsensusCore2 when built against the RootDir, but not when built against the library:

Compare:
"""
cmake ..

<build stuff>

make check
~/pblaa/_build ~/pblaa
[ 12%] Built target pblaa
[ 64%] Built target pbbam
[ 73%] Built target pbccs
[ 93%] Built target pbconsensus
Scanning dependencies of target test_pblaa
[ 94%] Building CXX object tests/CMakeFiles/test_pblaa.dir/TestAmpliconAnalysisEndToEnd.cpp.o
[ 96%] Building CXX object tests/CMakeFiles/test_pblaa.dir/TestClusterSpec.cpp.o
[ 96%] Building CXX object tests/CMakeFiles/test_pblaa.dir/__/third-party/cpp-optparse/OptionParser.cpp.o
[ 97%] Building CXX object tests/CMakeFiles/test_pblaa.dir/__/_deps/ConsensusCore2/third-party/gmock-1.7.0/gmock-gtest-all.cc.o
[ 98%] Building CXX object tests/CMakeFiles/test_pblaa.dir/__/_deps/ConsensusCore2/third-party/gmock-1.7.0/gmock_main.cc.o
[100%] Linking CXX executable ../../tests/bin/test_pblaa
[100%] Built target test_pblaa
Scanning dependencies of target check
Running main() from gmock_main.cc
[==========] Running 3 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 1 test from EndToEndTest
[ RUN      ] EndToEndTest.Phi29
>|> 20151028 06:12:49.857 -|- INFO       -|- FindBarcodePairs -|- 47174501762304|| -|- Preprocessing files for Barcode pairs ... 
>|> 20151028 06:12:49.860 -|- INFO       -|- FindBarcodePairs -|- 47174501762304|| -|- done, found 3, took 0.002s
>|> 20151028 06:12:49.860 -|- INFO       -|- DataSet -|- 47174501762304|| -|- Barcode '0--0', beginning subread filtering
>|> 20151028 06:12:49.864 -|- INFO       -|- DataSet -|- 47174501762304|| -|- Barcode '0--0', filtered from 120 total subreads
>|> 20151028 06:12:49.864 -|- INFO       -|- DataSet -|- 47174501762304|| -|- Barcode '0--0', found 40 post-filter subreads
>|> 20151028 06:12:49.864 -|- INFO       -|- DataSet -|- 47174501762304|| -|- Barcode '0--0', subread filtering took 0.004s
>|> 20151028 06:12:49.870 -|- INFO       -|- GeneCluster -|- 47174501762304|| -|- Barcode '0--0', aligning 40 subreads
>|> 20151028 06:12:50.047 -|- INFO       -|- GeneCluster -|- 47174501762304|| -|- Barcode '0--0', subread alignment took 0.176s
>|> 20151028 06:12:50.047 -|- INFO       -|- GeneCluster -|- 47174501762304|| -|- Barcode '0--0', coarse clustering on alignment results
>|> 20151028 06:12:50.049 -|- INFO       -|- GeneCluster -|- 47174501762304|| -|- Barcode '0--0', coarse clustering took 0.002s
>|> 20151028 06:12:50.049 -|- INFO       -|- GeneCluster -|- 47174501762304|| -|- Barcode '0--0', coarse clustering generated 1 clusters
>|> 20151028 06:12:50.049 -|- INFO       -|- GeneCluster -|- 47174501762304|| -|- Barcode '0--0', ranking subreads on clustering results
>|> 20151028 06:12:50.090 -|- INFO       -|- GeneCluster -|- 47174501762304|| -|- Barcode '0--0', subread ranking took 0.04s
>|> 20151028 06:12:50.090 -|- INFO       -|- GeneClusterConsensus -|- 47174501762304|| -|- Barcode '0--0', analyzing clustering results
>|> 20151028 06:12:50.090 -|- INFO       -|- SingleClusterConsensus -|- 47174501762304|| -|- Barcode '0--0', analyzing Cluster #0
>|> 20151028 06:12:56.815 -|- INFO       -|- SingleClusterConsensus -|- 47174501762304|| -|- Barcode '0--0', Cluster #0 analyzed in 6.724s
>|> 20151028 06:12:58.960 -|- INFO       -|- GeneClusterConsensus -|- 47174501762304|| -|- Barcode '0--0', finished analyzing clustering results8.869s
>|> 20151028 06:12:58.960 -|- INFO       -|- WriteResults -|- 47174501762304|| -|- Writing 1 result sequences to file
>|> 20151028 06:12:58.964 -|- INFO       -|- DataSet -|- 47174501762304|| -|- Barcode '1--1', beginning subread filtering
>|> 20151028 06:12:58.968 -|- INFO       -|- DataSet -|- 47174501762304|| -|- Barcode '1--1', filtered from 120 total subreads
>|> 20151028 06:12:58.968 -|- INFO       -|- DataSet -|- 47174501762304|| -|- Barcode '1--1', found 40 post-filter subreads
>|> 20151028 06:12:58.968 -|- INFO       -|- DataSet -|- 47174501762304|| -|- Barcode '1--1', subread filtering took 0.004s
>|> 20151028 06:12:58.975 -|- INFO       -|- GeneCluster -|- 47174501762304|| -|- Barcode '1--1', aligning 40 subreads
>|> 20151028 06:12:59.317 -|- INFO       -|- GeneCluster -|- 47174501762304|| -|- Barcode '1--1', subread alignment took 0.342s
>|> 20151028 06:12:59.318 -|- INFO       -|- GeneCluster -|- 47174501762304|| -|- Barcode '1--1', coarse clustering on alignment results
>|> 20151028 06:12:59.321 -|- INFO       -|- GeneCluster -|- 47174501762304|| -|- Barcode '1--1', coarse clustering took 0.003s
>|> 20151028 06:12:59.321 -|- INFO       -|- GeneCluster -|- 47174501762304|| -|- Barcode '1--1', coarse clustering generated 2 clusters
>|> 20151028 06:12:59.321 -|- INFO       -|- GeneCluster -|- 47174501762304|| -|- Barcode '1--1', ranking subreads on clustering results
>|> 20151028 06:12:59.434 -|- INFO       -|- GeneCluster -|- 47174501762304|| -|- Barcode '1--1', subread ranking took 0.112s
>|> 20151028 06:12:59.434 -|- INFO       -|- GeneClusterConsensus -|- 47174501762304|| -|- Barcode '1--1', analyzing clustering results
>|> 20151028 06:12:59.434 -|- INFO       -|- SingleClusterConsensus -|- 47174501762304|| -|- Barcode '1--1', analyzing Cluster #0
>|> 20151028 06:13:08.676 -|- INFO       -|- SingleClusterConsensus -|- 47174501762304|| -|- Barcode '1--1', Cluster #0 analyzed in 9.241s
>|> 20151028 06:13:11.188 -|- INFO       -|- GeneClusterConsensus -|- 47174501762304|| -|- Barcode '1--1', finished analyzing clustering results11.754s
>|> 20151028 06:13:11.189 -|- INFO       -|- WriteResults -|- 47174501762304|| -|- Writing 1 result sequences to file
>|> 20151028 06:13:11.194 -|- INFO       -|- DataSet -|- 47174501762304|| -|- Barcode '2--2', beginning subread filtering
>|> 20151028 06:13:11.198 -|- INFO       -|- DataSet -|- 47174501762304|| -|- Barcode '2--2', filtered from 120 total subreads
>|> 20151028 06:13:11.198 -|- INFO       -|- DataSet -|- 47174501762304|| -|- Barcode '2--2', found 40 post-filter subreads
>|> 20151028 06:13:11.198 -|- INFO       -|- DataSet -|- 47174501762304|| -|- Barcode '2--2', subread filtering took 0.004s
>|> 20151028 06:13:11.206 -|- INFO       -|- GeneCluster -|- 47174501762304|| -|- Barcode '2--2', aligning 40 subreads
>|> 20151028 06:13:11.438 -|- INFO       -|- GeneCluster -|- 47174501762304|| -|- Barcode '2--2', subread alignment took 0.231s
>|> 20151028 06:13:11.438 -|- INFO       -|- GeneCluster -|- 47174501762304|| -|- Barcode '2--2', coarse clustering on alignment results
>|> 20151028 06:13:11.440 -|- INFO       -|- GeneCluster -|- 47174501762304|| -|- Barcode '2--2', coarse clustering took 0.002s
>|> 20151028 06:13:11.440 -|- INFO       -|- GeneCluster -|- 47174501762304|| -|- Barcode '2--2', coarse clustering generated 1 clusters
>|> 20151028 06:13:11.440 -|- INFO       -|- GeneCluster -|- 47174501762304|| -|- Barcode '2--2', ranking subreads on clustering results
>|> 20151028 06:13:11.481 -|- INFO       -|- GeneCluster -|- 47174501762304|| -|- Barcode '2--2', subread ranking took 0.04s
>|> 20151028 06:13:11.482 -|- INFO       -|- GeneClusterConsensus -|- 47174501762304|| -|- Barcode '2--2', analyzing clustering results
>|> 20151028 06:13:11.482 -|- INFO       -|- SingleClusterConsensus -|- 47174501762304|| -|- Barcode '2--2', analyzing Cluster #0
>|> 20151028 06:13:17.573 -|- INFO       -|- SingleClusterConsensus -|- 47174501762304|| -|- Barcode '2--2', Cluster #0 analyzed in 6.091s
>|> 20151028 06:13:19.723 -|- INFO       -|- GeneClusterConsensus -|- 47174501762304|| -|- Barcode '2--2', finished analyzing clustering results8.241s
>|> 20151028 06:13:19.723 -|- INFO       -|- WriteResults -|- 47174501762304|| -|- Writing 1 result sequences to file
[       OK ] EndToEndTest.Phi29 (29875 ms)
[----------] 1 test from EndToEndTest (29877 ms total)
"""

To:
"""
cmake -DPBCONSENSUS_INCLUDE_DIRS=/home/UNIXHOME/bbowman/p4/depot/software/smrtanalysis/bioinformatics/ext-vc/pivc/ConsensusCore2/include -DPBCONSENSUS_LIBRARIES=/home/UNIXHOME/bbowman/p4/depot/software/smrtanalysis/bioinformatics/ext-vc/pivc/ConsensusCore2/lib/libpbconsensus.a ..

<build stuff>

make check
[ 16%] Built target pblaa
[ 27%] Built target pbccs
[ 94%] Built target pbbam
Scanning dependencies of target test_pblaa
[ 95%] Building CXX object tests/CMakeFiles/test_pblaa.dir/TestAmpliconAnalysisEndToEnd.cpp.o
[ 96%] Building CXX object tests/CMakeFiles/test_pblaa.dir/TestClusterSpec.cpp.o
[ 97%] Building CXX object tests/CMakeFiles/test_pblaa.dir/__/third-party/cpp-optparse/OptionParser.cpp.o
[ 98%] Building CXX object tests/CMakeFiles/test_pblaa.dir/home/UNIXHOME/bbowman/p4/depot/software/smrtanalysis/bioinformatics/ext-vc/pivc/ConsensusCore2/third-party/gmock-1.7.0/gmock-gtest-all.cc.o
[100%] Building CXX object tests/CMakeFiles/test_pblaa.dir/home/UNIXHOME/bbowman/p4/depot/software/smrtanalysis/bioinformatics/ext-vc/pivc/ConsensusCore2/third-party/gmock-1.7.0/gmock_main.cc.o
Linking CXX executable ../../tests/bin/test_pblaa
[100%] Built target test_pblaa
Scanning dependencies of target check
Running main() from gmock_main.cc
[==========] Running 3 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 1 test from EndToEndTest
[ RUN      ] EndToEndTest.Phi29
>|> 20151028 07:00:05.454 -|- INFO       -|- FindBarcodePairs -|- 47437113239488|| -|- Preprocessing files for Barcode pairs ... 
>|> 20151028 07:00:05.458 -|- INFO       -|- FindBarcodePairs -|- 47437113239488|| -|- done, found 3, took 0.004s
>|> 20151028 07:00:05.458 -|- INFO       -|- DataSet -|- 47437113239488|| -|- Barcode '0--0', beginning subread filtering
>|> 20151028 07:00:05.464 -|- INFO       -|- DataSet -|- 47437113239488|| -|- Barcode '0--0', filtered from 120 total subreads
>|> 20151028 07:00:05.464 -|- INFO       -|- DataSet -|- 47437113239488|| -|- Barcode '0--0', found 40 post-filter subreads
>|> 20151028 07:00:05.464 -|- INFO       -|- DataSet -|- 47437113239488|| -|- Barcode '0--0', subread filtering took 0.005s
>|> 20151028 07:00:05.472 -|- INFO       -|- GeneCluster -|- 47437113239488|| -|- Barcode '0--0', aligning 40 subreads
>|> 20151028 07:00:05.972 -|- INFO       -|- GeneCluster -|- 47437113239488|| -|- Barcode '0--0', subread alignment took 0.499s
>|> 20151028 07:00:05.972 -|- INFO       -|- GeneCluster -|- 47437113239488|| -|- Barcode '0--0', coarse clustering on alignment results
>|> 20151028 07:00:05.976 -|- INFO       -|- GeneCluster -|- 47437113239488|| -|- Barcode '0--0', coarse clustering took 0.004s
>|> 20151028 07:00:05.976 -|- INFO       -|- GeneCluster -|- 47437113239488|| -|- Barcode '0--0', coarse clustering generated 1 clusters
>|> 20151028 07:00:05.976 -|- INFO       -|- GeneCluster -|- 47437113239488|| -|- Barcode '0--0', ranking subreads on clustering results
>|> 20151028 07:00:05.987 -|- INFO       -|- GeneCluster -|- 47437113239488|| -|- Barcode '0--0', subread ranking took 0.01s
>|> 20151028 07:00:05.988 -|- INFO       -|- GeneClusterConsensus -|- 47437113239488|| -|- Barcode '0--0', analyzing clustering results
>|> 20151028 07:00:05.988 -|- INFO       -|- SingleClusterConsensus -|- 47437113239488|| -|- Barcode '0--0', analyzing Cluster #0
unknown file: Failure
C++ exception with description "chemistry not found: 'P6-C4'" thrown in the test body.
[  FAILED  ] EndToEndTest.Phi29 (14275 ms)
[----------] 1 test from EndToEndTest (14275 ms total)
"""

**Comment by evolvedmicrobe** [comment]
@bnbowman : Is this still relevant?

**Comment by nlhepler** [comment]
This is a linking issue (namely if you don't use the -force_load or -Wl,-whole-archive) the symbols for the built-in chemistry table are stripped as unused code. Closing
