### ISSUE TITLE
Error at install

### ISSUE THREAD

**Issue by SethM55** [PacificBiosciences/ConsensusCore2#12]
Hello,

When trying to install ConsensusCore2 as a prerequiste for GenomicConsensus I found no instructions on how to do so.  Given the lack of a configure or Makefile file I presumed it was the common python command of:
python setup.py install

This gives the following error:
Running command cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DPYTHON_SWIG=1 -DPYTHON_EXECUTABLE=/usr/bin/python /genome/Apps/ConsensusCore2
Traceback (most recent call last):
  File "setup.py", line 47, in <module>
    retcode = Popen(cmds, cwd=buildDir, env=env).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Every file or directory listed in the above is, however, valid.  What do I need to look at to correct the error?

**Comment by SethM55** [comment]
Ahh, good to know, the instructions on GenomicConsensus currently say that pbcore, ConsensusCore, and ConsensusCore2 are prerequisites.

Looks like I don't fit one of those definitions of "should"  I updated boost, swig, and cmake but got stuck at an attempt on install, with:
make[2]: *** No rule to make target `/usr/lib/x86_64-linux-gnu/libpython2.7.so', needed by `/genome/Apps/ConsensusCore2/swig/lib/_ConsensusCore2.so'.  Stop.

Thanks for your help, nonetheless!

**Comment by nlhepler** [comment]
Ah, you won't need ConsensusCore2 for using quiver, only for a new algorithm we're developing.

That error is curious, might I ask what kind of system you're running on?

**Comment by SethM55** [comment]
uname -a
Linux Banting 3.16.0-53-generic #72~14.04.1-Ubuntu SMP Fri Nov 6 18:17:23 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Did you want hardware specs as well?

**Comment by nlhepler** [comment]
No, that shouldn't be necessary. Looks like an ubuntu system, or at least derived from 14.04, which is what we run on..

Could you verify that /usr/lib/x86_64-linux-gnu/libpython2.7.so doesn't exist?

**Comment by SethM55** [comment]
I got interrupted on Firday and forgot about this, sorry.  I checked libpython2.7.so does exist, but it's being reported as a broken link.
