### ISSUE TITLE
On A/B fill, beta fill often uses too much memory

### ISSUE THREAD

**Issue by evolvedmicrobe** [PacificBiosciences/ConsensusCore2#2]
I will investigate this later, just leaving this as a note.  It's very common for the Beta to be 10 times the size of the Alpha though, should be tracked down.

Alpha Used: 20247  Beta Used:  20774
Alpha Used: 33385  Beta Used:  189656
Alpha Used: 20182  Beta Used:  20698
Alpha Used: 19689  Beta Used:  19872
Alpha Used: 20060  Beta Used:  20405
Alpha Used: 19757  Beta Used:  19994
Alpha Used: 19984  Beta Used:  20229
Alpha Used: 19961  Beta Used:  20771
Alpha Used: 21162  Beta Used:  20771
Alpha Used: 20291  Beta Used:  20788
Alpha Used: 19575  Beta Used:  19762
Alpha Used: 34152  Beta Used:  209818
Alpha Used: 42000  Beta Used:  605472
Alpha Used: 19811  Beta Used:  20440
Alpha Used: 19488  Beta Used:  19991
Alpha Used: 17591  Beta Used:  17980

**Comment by evolvedmicrobe** [comment]
Had a chance to look a bit more into this, it appears to be an upstream issue.

Basically, when a lot of "Single Molecule Weirdness" occurs, the alpha goes off the rails, which then forces the beta too as well.  An example plot is shown below.  You can see a large bubble in the middle forces the alpha to go far off the diagonal, and it doesn't clamp back until the beta occurs.  This behavior is relatively common, and it introduce a big performance hit, particularly for very long templates.

![matrixfailure](https://cloud.githubusercontent.com/assets/1330626/11229886/ebb463d4-8d4e-11e5-813a-e195b21fea68.png)

Although there are several things we could do to ameleriorate this downstream, there is no mechanistic reason we should be producing either long inserts or large deletions.  The alignment for this "bubble" is shown below.  Clearly we need to get rid of this type of thing, it's nonsense.

![image](https://cloud.githubusercontent.com/assets/1330626/11229899/14119982-8d4f-11e5-9150-48b1da5f9ed3.png)

**Comment by nlhepler** [comment]
Yes, this kind of thing is known about (hence the extra flip-flopping). It would be great if we could save the diagonals so we don't go through the entire back-and-forth when it does happen, but I can't see a way to do that presently without rethinking the whole banding strategy..

**Comment by evolvedmicrobe** [comment]
Yeah agreed, we'll fix this in primary base calling.  Closing for now.
