### ISSUE TITLE
InRange Function is Broken - SIGABRT

### ISSUE THREAD

**Issue by evolvedmicrobe** [PacificBiosciences/ConsensusCore2#3]
Exceptions in LAA are being generated under the following conditions during polishing.  Assume a template is of length 1000, and a subread maps from 100-900.  Because all of the subread maps, it is considered to be "pinned" at the start and the end.

Next we go to test a mutation, say at position 901 on the template.  This is outside of the region on this subread, so it should not be used for scoring.  However, because the InRange function below is used to check this, if the subread is "pinned", then it considered to overlap, it attempts to score a mutation outside of the template, and all fails.  

      // inline function impls
      bool AbstractTemplate::InRange(const size_t start, const size_t end) const
      {
          if ((pinStart_ || start_ < end) && (pinEnd_ || start < end_)) return true;
          return false;
      }

I am not sure why the pinning affects the InRange function here, so will wait to find out more before editing.

**Comment by evolvedmicrobe** [comment]
Test case fixed.

**Comment by nlhepler** [comment]
@evolvedmicrobe, could you point to the testcase fixed. I could see a bug lurking here.

**Comment by nlhepler** [comment]
You're absolutely right. I'm going to fix this now. =/

**Comment by evolvedmicrobe** [comment]
Hey Lance,  there were a couple of bugs lurking, let's chat.
