### ISSUE TITLE
assert fail in tests (debug build)

### ISSUE THREAD

**Issue by dalexander** [PacificBiosciences/ConsensusCore2#30]
[ RUN      ] TemplateTest.NullTemplate
Assertion failed: (tpl_.size() == end_ - start_), function ApplyMutation, file /Users/dalexander/Dropbox/Sources/git-pbi/ConsensusCore2/src/Template.cpp, line 284.

**Comment by nlhepler** [comment]
We now test under debug builds, and this was fixed in 41ea42804e076a309556aee7f266878db64c5422

**Comment by dalexander** [comment]
bravo, sir
