### ISSUE TITLE
python setup.py clean

### ISSUE THREAD

**Issue by dalexander** [PacificBiosciences/ConsensusCore2#46]
This doesn't work reliably or correctly.  I just ran `python setup.py clean` and it built.

**Comment by nlhepler** [comment]
Yes. It always refreshes the C++ build before performing any distutils command. There's no really-reliable way to make it work across ```python setup.py``` and ```pip``` without just accepting this cost, even if all you're doing is building to clean it away. I tried a deeper integration but the hooks are just not well-defined and well-respected enough across the different tools to depend upon.
