### ISSUE TITLE
Documentation on Arrow

### ISSUE THREAD

**Issue by keyavi** [PacificBiosciences/ConsensusCore2#71]
Can you guys share some of the documentation for the HMM model used by the CCS algorithm?

**Comment by evolvedmicrobe** [comment]
Hi @keyavi,

I am writing up a manuscript as time allows, and thanks for asking! (it helps to prioritize it relative to all the other projects we have going on).  If you need some specific information sooner, feel free to reach out to me at ndelaney@pacb 

Cheers,
Nigel
